#spring.application.name=compensationAndLeaves.service.backend


server:
    port: 8081

spring:
    application:
        name: Compensation_Service
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: ""
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    h2:
        console:
            enabled: true
            path: /h2-console  # You can customize this path if needed

eureka:
    client:
        service-url:
            defaultZone: http://localhost:9000/eureka/
        register-with-eureka: true
        fetch-registry: true